# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 431c15e33042c4c2948285788ef8428ea5b79aedf3aec935f9d7c098da4fd4088fabefa9464cd3e0547b74d5cdba6a670ec917e11572a0846b7c5cf7c7afef3a

test:
  secret_key_base: 956d8b9110c14198c51db7757d3f1f33312ba8235a881cea6223cc2b043fa2f5554281c9bdfb120d8bcccf2d9a264b60b7dfd740b5d0a9fea6ccbd913430dbf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
